# general keybinds config file

set -g prefix C-s # remap leader key a.k.a prefix
set -sg escape-time 0 # 0ms to wait for escape key
setw -g mode-keys vi # vim mode embebed into tmux

# unbind old defaults
unbind r
unbind x
unbind [
unbind ]
unbind p
unbind n

# new bindings
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"
bind x kill-pane
bind v copy-mode
bind p paste-buffer
bind-key -n M-h previous-window
bind-key -n M-l next-window

# remap move keys between panels
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# remap to better control of panes and windows
bind c new-window -c "#{pane_current_path}" # keep same path when creating new window
bind % split-window -h -c "#{pane_current_path}" # keep same path when spliting window horizontally
bind '"' split-window -v -c "#{pane_current_path}" # keep same path when spliting window vertically

# remap for creatin scratch buffer
bind-key b new-window -n scratch "NVIM_SCRATCH=1 nvim +'enew | file [Scratch] | setlocal buftype=nofile bufhidden=wipe noswapfile nonumber norelativenumber | startinsert'"

# use xclip package to copy selected text into operating system buffer
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi / command-prompt -i -p "search down:" "send -X search-forward-incremental \"%%%\"" # enable incremental search down with /
bind-key -T copy-mode-vi ? command-prompt -i -p "search up:" "send -X search-backward-incremental \"%%%\"" # enable incremental search up with ?

bind-key n send-keys -l 'task add "<++>" proj: due: scheduled: priority: depends:'
