# general options config file

set-option -g status-position top # move status var to top
set-option -a terminal-features 'xterm-256color:RGB' # fix colors in the terminal

# set default shell
set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh
