# general styles config file

# styles for statusbar or command line
set -g status-style "fg=#7aa2f7,bg=#17033e"
set -g status-left "#[fg=#7dcfff,bold] [#S] "
set -g status-left-length 100
set -g mode-style "fg=#c0caf5,bg=#2d4f67,bold"
set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#7aa2f7"
set -g message-style "fg=#7aa2f7,bg=#170229,bold"
set -g message-command-style "fg=#7dcfff,bg=#170229,bold"
