#   ________  _____  ___  __    __________  _   __________________
#  /_  __/  |/  / / / / |/ /   / ____/ __ \/ | / / ____/  _/ ____/
#   / / / /|_/ / / / /|   /   / /   / / / /  |/ / /_   / // / __
#  / / / /  / / /_/ //   |   / /___/ /_/ / /|  / __/ _/ // /_/ /
# /_/ /_/  /_/\____//_/|_|   \____/\____/_/ |_/_/   /___/\____/

# unbind old defaults
unbind r
unbind x
unbind [
unbind ]
unbind p
unbind n

# new bindings
bind r source-file ~/.config/tmux/tmux.conf
bind x kill-pane
bind v copy-mode
bind p paste-buffer
bind-key -n M-h previous-window
bind-key -n M-l next-window

# remap move keys between panels
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# remap to better control of panes and windows
bind c new-window -c "#{pane_current_path}" # keep same path when creating new window
bind % split-window -h -c "#{pane_current_path}" # keep same path when spliting window horizontally
bind '"' split-window -v -c "#{pane_current_path}" # keep same path when spliting window vertically

# remap for creatin scratch buffer
bind-key b new-window -n scratch "NVIM_SCRATCH=1 nvim +'enew | file [Scratch] | setlocal buftype=nofile bufhidden=wipe noswapfile nonumber norelativenumber | startinsert'"

# open lf for navigation
bind e send-keys "lf" C-m

set -g prefix C-s # remap leader key a.k.a prefix
set -sg escape-time 0 # 0ms to wait for escape key
setw -g mode-keys vi # vim mode embebed into tmux
set-option -g status-position top # move status var to top
set-option -a terminal-features 'xterm-256color:RGB' # fix colors in the terminal

# use xclip package to copy selected text into operating system buffer
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi / command-prompt -i -p "search down:" "send -X search-forward-incremental \"%%%\"" # enable incremental search down with /
bind-key -T copy-mode-vi ? command-prompt -i -p "search up:" "send -X search-backward-incremental \"%%%\"" # enable incremental search up with ?

# set default shell
set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh

# styles
set -g status-style "fg=#7aa2f7,bg=#17033e"
set -g status-left "#[fg=#7dcfff,bold] [#S] "
set -g status-left-length 100
set -g mode-style "fg=#c0caf5,bg=#2d4f67,bold"
set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#7aa2f7"
set -g message-style "fg=#7aa2f7,bg=#170229,bold"
set -g message-command-style "fg=#7dcfff,bg=#170229,bold"

